CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.admins (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pin_number varchar(50) NOT NULL,
  archived_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.students (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id varchar(50) NOT NULL UNIQUE,
  student_name varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  parent_name varchar(255) NOT NULL,
  contact_number varchar(50) NOT NULL,
  profile_photo text NULL,
  status varchar(20) NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'inactive', 'archived')),
  archived_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_students_name
  ON public.students (student_name);

CREATE TABLE IF NOT EXISTS public.instructor_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_uid varchar(80) NOT NULL UNIQUE,
  username varchar(120) NOT NULL UNIQUE,
  password varchar(255) NOT NULL,
  display_name varchar(255) NOT NULL,
  pin_number varchar(50) NULL,
  contact_number varchar(50) NULL,
  profile_photo text NULL,
  role_title varchar(120) NOT NULL DEFAULT 'Clinical Instructor',
  status varchar(20) NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'inactive', 'archived')),
  archived_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.school_years (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label varchar(20) NOT NULL UNIQUE,
  start_year smallint NOT NULL,
  end_year smallint NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'inactive', 'archived')),
  created_by varchar(80) NULL,
  archived_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT school_years_consecutive_check CHECK (end_year = start_year + 1)
);

CREATE INDEX IF NOT EXISTS idx_school_year_status
  ON public.school_years (status, archived_at);

CREATE TABLE IF NOT EXISTS public.student_blocks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_year_id bigint NOT NULL REFERENCES public.school_years(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  label varchar(120) NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'inactive', 'archived')),
  created_by varchar(80) NULL,
  archived_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_block_year_label UNIQUE (school_year_id, label)
);

CREATE TABLE IF NOT EXISTS public.student_block_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id varchar(50) NOT NULL REFERENCES public.students(student_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  block_id bigint NOT NULL REFERENCES public.student_blocks(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  assigned_by varchar(80) NULL,
  archived_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_student_block UNIQUE (student_id)
);

CREATE INDEX IF NOT EXISTS idx_assignment_block
  ON public.student_block_assignments (block_id, archived_at);

CREATE TABLE IF NOT EXISTS public.api_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash char(64) NOT NULL UNIQUE,
  role varchar(20) NOT NULL CHECK (role IN ('admin', 'instructor', 'student')),
  user_uid varchar(80) NOT NULL,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_session_lookup
  ON public.api_sessions (token_hash, expires_at, revoked_at);

CREATE INDEX IF NOT EXISTS idx_session_user
  ON public.api_sessions (role, user_uid);

CREATE TABLE IF NOT EXISTS public.audit_trail (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_role varchar(20) NOT NULL
    CHECK (actor_role IN ('admin', 'instructor', 'student', 'system')),
  actor_uid varchar(80) NULL,
  action_name varchar(80) NOT NULL,
  entity_type varchar(80) NOT NULL,
  entity_uid varchar(120) NULL,
  details jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_created
  ON public.audit_trail (created_at);

CREATE INDEX IF NOT EXISTS idx_audit_entity
  ON public.audit_trail (entity_type, entity_uid);

CREATE INDEX IF NOT EXISTS idx_audit_activity_timeline
  ON public.audit_trail (entity_type, entity_uid, created_at);

CREATE INDEX IF NOT EXISTS idx_audit_actor
  ON public.audit_trail (actor_role, actor_uid);

CREATE TABLE IF NOT EXISTS public.procedures (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  procedure_key varchar(80) NOT NULL UNIQUE,
  procedure_name varchar(255) NOT NULL UNIQUE,
  display_order integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.case_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id varchar(50) NOT NULL REFERENCES public.students(student_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  student_name varchar(255) NOT NULL,
  instructor_uid varchar(80) NULL,
  instructor_name varchar(255) NULL,
  academic_year varchar(20) NULL,
  procedure_key varchar(80) NOT NULL REFERENCES public.procedures(procedure_key)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  procedure_name varchar(255) NOT NULL,
  case_no varchar(100) NULL,
  complete_diagnosis text NULL,
  date_time_performed timestamptz NULL,
  patient_name varchar(255) NULL,
  patient_address varchar(255) NULL,
  facility_name varchar(255) NULL,
  facility_address varchar(255) NULL,
  facility_contact_number varchar(50) NULL,
  supervisor_printed_name varchar(255) NULL,
  supervisor_contact_number varchar(50) NULL,
  supervisor_position_designation varchar(255) NULL,
  supervisor_license_no varchar(100) NULL,
  supervisor_license_expiry_date date NULL,
  teacher_remarks text NULL,
  checked_by varchar(255) NULL,
  checked_at timestamptz NULL,
  record_status varchar(20) NOT NULL DEFAULT 'submitted'
    CHECK (record_status IN ('submitted', 'reviewed', 'verified', 'needs_revision', 'invalid', 'archived')),
  archived_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cases_student
  ON public.case_records (student_id);

CREATE INDEX IF NOT EXISTS idx_cases_procedure
  ON public.case_records (procedure_key);

CREATE INDEX IF NOT EXISTS idx_cases_academic_year
  ON public.case_records (academic_year);

CREATE INDEX IF NOT EXISTS idx_cases_date
  ON public.case_records (date_time_performed);

CREATE TABLE IF NOT EXISTS public.case_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id bigint NOT NULL REFERENCES public.case_records(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  author_uid varchar(80) NULL,
  author_name varchar(255) NOT NULL,
  author_role varchar(20) NOT NULL DEFAULT 'instructor'
    CHECK (author_role IN ('instructor', 'admin')),
  comment_text text NOT NULL,
  source_key varchar(120) NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  archived_at timestamptz NULL,
  archived_by varchar(80) NULL
);

CREATE INDEX IF NOT EXISTS idx_case_comments_case
  ON public.case_comments (case_id, archived_at, created_at);

CREATE TABLE IF NOT EXISTS public.edit_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id varchar(50) NOT NULL REFERENCES public.students(student_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  procedure_key varchar(80) NOT NULL REFERENCES public.procedures(procedure_key)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  procedure_name varchar(255) NOT NULL,
  case_numbers jsonb NULL,
  status varchar(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected')),
  rejection_remarks text NULL,
  requested_at timestamptz NOT NULL DEFAULT now(),
  approved_at timestamptz NULL,
  rejected_at timestamptz NULL,
  archived_at timestamptz NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_edit_requests_student
  ON public.edit_requests (student_id);

CREATE INDEX IF NOT EXISTS idx_edit_requests_status
  ON public.edit_requests (status);

CREATE INDEX IF NOT EXISTS idx_edit_requests_procedure
  ON public.edit_requests (procedure_key);

CREATE TABLE IF NOT EXISTS public.edit_permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id varchar(50) NOT NULL REFERENCES public.students(student_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  procedure_key varchar(80) NOT NULL REFERENCES public.procedures(procedure_key)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  approved boolean NOT NULL DEFAULT false,
  approved_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_edit_permission UNIQUE (student_id, procedure_key)
);

CREATE TABLE IF NOT EXISTS public.notification_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type varchar(80) NOT NULL,
  student_id varchar(50) NULL REFERENCES public.students(student_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  procedure_key varchar(80) NULL,
  procedure_type varchar(255) NULL,
  case_no varchar(100) NULL,
  request_id bigint NULL REFERENCES public.edit_requests(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  message text NULL,
  remarks text NULL,
  meta jsonb NULL,
  archived_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notifications_created
  ON public.notification_history (created_at);

CREATE INDEX IF NOT EXISTS idx_notifications_student
  ON public.notification_history (student_id);

CREATE INDEX IF NOT EXISTS idx_notifications_event
  ON public.notification_history (event_type);

CREATE INDEX IF NOT EXISTS idx_notifications_request
  ON public.notification_history (request_id);

CREATE TABLE IF NOT EXISTS public.chat_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id varchar(50) NOT NULL REFERENCES public.students(student_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  student_name varchar(255) NULL,
  instructor_id varchar(80) NULL,
  instructor_name varchar(255) NULL,
  sender_role varchar(20) NOT NULL DEFAULT 'student'
    CHECK (sender_role IN ('student', 'instructor')),
  sender_name varchar(255) NOT NULL,
  message text NOT NULL,
  read_by_student boolean NOT NULL DEFAULT false,
  read_by_instructor boolean NOT NULL DEFAULT false,
  archived_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_chat_student_created
  ON public.chat_messages (student_id, created_at);

CREATE INDEX IF NOT EXISTS idx_chat_unread_student
  ON public.chat_messages (student_id, read_by_student);

CREATE INDEX IF NOT EXISTS idx_chat_unread_instructor
  ON public.chat_messages (student_id, read_by_instructor);

CREATE TABLE IF NOT EXISTS public.school_year_archives (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_year varchar(20) NOT NULL UNIQUE,
  start_year smallint NOT NULL,
  end_year smallint NOT NULL,
  saved_by varchar(255) NULL,
  archive_payload jsonb NULL,
  saved_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT school_year_archives_consecutive_check CHECK (end_year = start_year + 1)
);

CREATE TABLE IF NOT EXISTS public.school_year_archive_procedures (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  archive_id bigint NOT NULL REFERENCES public.school_year_archives(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  procedure_key varchar(80) NOT NULL REFERENCES public.procedures(procedure_key)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  procedure_name varchar(255) NOT NULL,
  folder_name varchar(255) NOT NULL,
  records_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_archive_procedure UNIQUE (archive_id, procedure_key)
);

CREATE TABLE IF NOT EXISTS public.school_year_archive_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  archive_procedure_id bigint NOT NULL REFERENCES public.school_year_archive_procedures(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  case_record_id bigint NOT NULL REFERENCES public.case_records(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_archive_case UNIQUE (archive_procedure_id, case_record_id)
);

CREATE TABLE IF NOT EXISTS public.system_meta (
  meta_key varchar(80) PRIMARY KEY,
  meta_value jsonb NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS admins_set_updated_at ON public.admins;
CREATE TRIGGER admins_set_updated_at
BEFORE UPDATE ON public.admins
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS students_set_updated_at ON public.students;
CREATE TRIGGER students_set_updated_at
BEFORE UPDATE ON public.students
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS instructor_accounts_set_updated_at ON public.instructor_accounts;
CREATE TRIGGER instructor_accounts_set_updated_at
BEFORE UPDATE ON public.instructor_accounts
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS school_years_set_updated_at ON public.school_years;
CREATE TRIGGER school_years_set_updated_at
BEFORE UPDATE ON public.school_years
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS student_blocks_set_updated_at ON public.student_blocks;
CREATE TRIGGER student_blocks_set_updated_at
BEFORE UPDATE ON public.student_blocks
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS student_block_assignments_set_updated_at ON public.student_block_assignments;
CREATE TRIGGER student_block_assignments_set_updated_at
BEFORE UPDATE ON public.student_block_assignments
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS case_records_set_updated_at ON public.case_records;
CREATE TRIGGER case_records_set_updated_at
BEFORE UPDATE ON public.case_records
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS edit_requests_set_updated_at ON public.edit_requests;
CREATE TRIGGER edit_requests_set_updated_at
BEFORE UPDATE ON public.edit_requests
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS edit_permissions_set_updated_at ON public.edit_permissions;
CREATE TRIGGER edit_permissions_set_updated_at
BEFORE UPDATE ON public.edit_permissions
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

INSERT INTO public.admins (pin_number)
SELECT '123456'
WHERE NOT EXISTS (SELECT 1 FROM public.admins);

UPDATE public.admins
SET pin_number = '123456'
WHERE pin_number IS NULL OR btrim(pin_number) = '' OR pin_number = '000000';

INSERT INTO public.instructor_accounts (
  account_uid,
  username,
  password,
  display_name,
  pin_number
)
VALUES ('ins_default', 'instructor', '123456', 'Default Instructor', NULL)
ON CONFLICT (username) DO NOTHING;

INSERT INTO public.procedures (procedure_key, procedure_name, display_order)
VALUES
  ('delivery handled', 'Delivery Handled', 10),
  ('delivery assisted', 'Delivery Assisted', 20),
  ('internal exam', 'Internal Exam', 30),
  ('suturing', 'Suturing', 40),
  ('iv insertion', 'IV Insertion', 50)
ON CONFLICT (procedure_key) DO UPDATE
SET procedure_name = EXCLUDED.procedure_name,
    display_order = EXCLUDED.display_order;

CREATE OR REPLACE VIEW public.v_case_records_full AS
SELECT
  c.id,
  c.student_id,
  s.student_name AS current_student_name,
  c.student_name AS recorded_student_name,
  c.instructor_uid,
  c.instructor_name,
  c.academic_year,
  c.procedure_key,
  c.procedure_name,
  c.case_no,
  c.complete_diagnosis,
  c.date_time_performed,
  c.patient_name,
  c.patient_address,
  c.facility_name,
  c.facility_address,
  c.facility_contact_number,
  c.supervisor_printed_name,
  c.supervisor_contact_number,
  c.supervisor_position_designation,
  c.supervisor_license_no,
  c.supervisor_license_expiry_date,
  c.teacher_remarks,
  c.checked_by,
  c.checked_at,
  c.record_status,
  c.archived_at,
  c.created_at,
  c.updated_at
FROM public.case_records AS c
JOIN public.students AS s ON s.student_id = c.student_id;

CREATE OR REPLACE VIEW public.v_student_case_summary AS
SELECT
  s.student_id,
  s.student_name,
  COUNT(c.id) AS total_cases,
  COALESCE(SUM(
    CASE
      WHEN c.checked_by IS NOT NULL AND btrim(c.checked_by) <> '' THEN 1
      ELSE 0
    END
  ), 0) AS verified_cases,
  string_agg(DISTINCT c.procedure_name, ', ' ORDER BY c.procedure_name) AS procedures
FROM public.students AS s
LEFT JOIN public.case_records AS c ON c.student_id = s.student_id
GROUP BY s.student_id, s.student_name;

CREATE OR REPLACE VIEW public.v_school_year_procedure_summary AS
SELECT
  c.academic_year AS school_year,
  c.procedure_key,
  c.procedure_name,
  COUNT(*) AS total_records,
  COUNT(DISTINCT c.student_id) AS total_students,
  COALESCE(SUM(
    CASE
      WHEN c.checked_by IS NOT NULL AND btrim(c.checked_by) <> '' THEN 1
      ELSE 0
    END
  ), 0) AS verified_records
FROM public.case_records AS c
WHERE c.academic_year IS NOT NULL
  AND btrim(c.academic_year) <> ''
GROUP BY c.academic_year, c.procedure_key, c.procedure_name;
